// ./src/app/head.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Head() {
  return (
    <>
      <title>{String(metadata.title) ?? "Default Title"}</title>
      <meta
        name="description"
        content={String(metadata.description) ?? "Default description"}
      />
      {/* Add more meta tags as needed */}
    </>
  );
}
