import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "swiper/css"; // Import Swiper styles

import Footer from "./components/Footer";
import { diphylleia, montserratAlternates } from "./font";
import { SkeletonTheme } from "react-loading-skeleton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${diphylleia.variable} ${montserratAlternates.variable}`}
    >
      <body
        className={`${inter.className} text-black font-montserrat-alternates`}
      >
        <SkeletonTheme baseColor="#EEEEEE" highlightColor="#FFCC99">
          {children}
        </SkeletonTheme>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
